### ISSUE TITLE
Fails to run on current Godot 4 Build

### ISSUE THREAD

**Issue by nonfatmatt** [godot-extended-libraries/godot-interpolated-camera3d-demo#1]
Parser Error: Identifier "BUTTON_LEFT" not declared in the current scope. (Line 25, player.gd). 

2bd89ac is the current pull of master that I tested it against.

**Comment by DanaFo** [comment]
Sorry what's the work around here if I want to detect button_left is clicked?

**Comment by Calinou** [comment]
> Sorry what's the work around here if I want to detect button_left is clicked?

`BUTTON_LEFT` is now `MOUSE_BUTTON_LEFT`.

Tip: Use **Search Help** in the top-right corner of the script editor to find this in the future :slightly_smiling_face:

**Comment by DanaFo** [comment]
> 

Ah cheers! Sorry I usually use VS Code and I literally googled for fifteen minutes and checked the docs this way and found nothing.

**Comment by Calinou** [comment]
Fixed by https://github.com/godot-extended-libraries/godot-interpolated-camera3d-demo/commit/6b7179d058975348e55f55f7caccad76b84c69f3.
