### ISSUE TITLE
What is the use case of a 3D InterpolatedCamera?

### ISSUE THREAD

**Issue by GeorgeS2019** [godot-extended-libraries/godot-interpolated-camera3d-demo#2]
This is a great plugin. IT is just not clear for new users interested on 3D to use it.

**InterpolatedCamera** is a 3D camera that smoothly follows a target (interpolates).

[Demo](http://kidscancode.org/godot_recipes/3d/interpolated_camera/)

**Comment by Calinou** [comment]
InterpolatedCamera is mainly useful in third-person games when you want a camera to follow the player smoothly. A camera that follows the player instantly just doesn't feel good in most third-person games :slightly_smiling_face:
